php:
  preset: laravel
  version: 8.1
  disabled:
    - no_unused_imports
  finder:
    not-name:
      - index.php
    not-path:
      - "bootstrap"
      - "config"
      - "public"
      - "storage"
      - "resources"
      - "tests"
js:
  finder:
    not-name:
      - webpack.mix.js
      - base64.js
      - "*.min.js"
      - "*.min.js.map"
    not-path:
      - "bootstrap"
      - "config"
      - "storage"
      - "resources"
      - "tests"
css:
  finder:
    not-name:
      - bootstrap-icons.css
      - "*.scss"
      - "*.min.css"
      - "*.min.css.map"
    not-path:
      - "bootstrap"
      - "config"
      - "storage"
      - "resources"
      - "tests"
